package arquitecturaproyecto;

import java.awt.*;
import java.awt.event.ActionEvent;

public class loginRegistro extends javax.swing.JFrame {
    
    static login pnlLogin = new login();
    static registro pnlRegistro = new registro();

    public loginRegistro() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Iniciar Sesión");
        this.getContentPane().setLayout(new BorderLayout());
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.add(pnlLogin, BorderLayout.CENTER);
        this.pack();
        
        pnlLogin.getBttnRegistrarse().addActionListener((ActionEvent e) -> {
            changeToRegister();
        });
        pnlLogin.getBttnIniciarSesion().addActionListener((ActionEvent e) -> {
            // Revisar en la BD del usuario.
            navigateToPrincipal();
        });
        pnlRegistro.getBttnRegresar().addActionListener((ActionEvent e) -> {
            changeToLogin();
        });
    }
    
    private void changeToRegister() {
        this.remove(pnlLogin);
        this.setTitle("Registrarse");
        this.add(pnlRegistro, BorderLayout.CENTER);
        this.pack();
    }
    
    private void changeToLogin() {
        this.remove(pnlRegistro);
        this.setTitle("Iniciar Sesión");
        this.add(pnlLogin, BorderLayout.CENTER);
        this.pack();
    }
    
    private void navigateToPrincipal() {
        principal frmPrincipal = new principal();
        frmPrincipal.setExtendedState(MAXIMIZED_BOTH);
        frmPrincipal.setVisible(true);
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1920, 1080));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1253, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 589, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
