/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package arquitecturaproyecto;

import javax.swing.*;

/**
 *
 * @author ceffy
 */
public class menu extends javax.swing.JPanel {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenu = new javax.swing.JPanel();
        bttnLogout = new javax.swing.JButton();
        pnlNavigation = new javax.swing.JPanel();
        bttnPerfil = new javax.swing.JButton();
        bttnForo = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        pnlMenu.setBackground(new java.awt.Color(255, 255, 255));
        pnlMenu.setLayout(new java.awt.BorderLayout());

        bttnLogout.setText("Cerrar sesión");
        bttnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnLogoutActionPerformed(evt);
            }
        });
        pnlMenu.add(bttnLogout, java.awt.BorderLayout.PAGE_END);

        pnlNavigation.setLayout(new java.awt.BorderLayout());

        bttnPerfil.setText("Perfil");
        pnlNavigation.add(bttnPerfil, java.awt.BorderLayout.CENTER);

        bttnForo.setText("Foro");
        pnlNavigation.add(bttnForo, java.awt.BorderLayout.PAGE_START);

        pnlMenu.add(pnlNavigation, java.awt.BorderLayout.PAGE_START);

        add(pnlMenu, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void bttnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnForo;
    private javax.swing.JButton bttnLogout;
    private javax.swing.JButton bttnPerfil;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlNavigation;
    // End of variables declaration//GEN-END:variables


    public JButton getBttnForo() {
        return bttnForo;
    }

    public JButton getBttnLogout() {
        return bttnLogout;
    }

    public JButton getBttnPerfil() {
        return bttnPerfil;
    }
}
