package arquitecturaproyecto;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;

public class principal extends javax.swing.JFrame {
    
    foro pnlForo = new foro();
    eventos pnlEvento = new eventos();
    perfil pnlPerfil = new perfil();

    public principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Perfil");
        this.getContentPane().setLayout(new BorderLayout());
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        pnlForo.setVisible(false);
        pnlEvento.setVisible(false);
        pnlPerfil.setVisible(true);
        this.add(pnlPerfil, BorderLayout.CENTER);
        this.add(pnlMenu, BorderLayout.EAST);
        bttnPerfil.setVisible(false);
        this.validate();
        
        bttnPerfil.addActionListener((ActionEvent e) -> {
            changeToPerfil();
        });
        bttnForo.addActionListener((ActionEvent e) -> {
            changeToForo();
        });
        bttnLogout.addActionListener((ActionEvent e) -> {
            navigateToLogin();
        });
    }
    
    private void changeToForo() {
        pnlForo.setVisible(true);
        pnlEvento.setVisible(false);
        pnlPerfil.setVisible(false);
        
        bttnForo.setVisible(false);
        bttnPerfil.setVisible(true);
        this.setTitle("Foro de Eventos");
        this.add(pnlForo, BorderLayout.CENTER);
        this.validate();
    }
    private void changeToPerfil() {
        pnlForo.setVisible(false);
        pnlEvento.setVisible(false);
        pnlPerfil.setVisible(true);
        
        bttnForo.setVisible(true);
        bttnPerfil.setVisible(false);
        this.setTitle("Perfil");
        this.add(pnlPerfil, BorderLayout.CENTER);
        this.validate();
    }
    private void changeToEvento() {
        pnlForo.setVisible(false);
        pnlEvento.setVisible(true);
        pnlPerfil.setVisible(false);
        this.setTitle("Perfil");
        this.add(pnlEvento, BorderLayout.CENTER);
        this.validate();
    }
    private void navigateToLogin() {
        loginRegistro frmLogin = new loginRegistro();
        frmLogin.setExtendedState(MAXIMIZED_BOTH);
        frmLogin.setVisible(true);
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenu = new javax.swing.JPanel();
        bttnLogout = new javax.swing.JButton();
        pnlNavigation = new javax.swing.JPanel();
        bttnPerfil = new javax.swing.JButton();
        bttnForo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1920, 1080));

        pnlMenu.setBackground(new java.awt.Color(255, 255, 255));
        pnlMenu.setLayout(new java.awt.BorderLayout());

        bttnLogout.setText("Cerrar sesión");
        bttnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnLogoutActionPerformed(evt);
            }
        });
        pnlMenu.add(bttnLogout, java.awt.BorderLayout.PAGE_END);

        pnlNavigation.setLayout(new java.awt.BorderLayout());

        bttnPerfil.setText("Perfil");
        pnlNavigation.add(bttnPerfil, java.awt.BorderLayout.CENTER);

        bttnForo.setText("Foro");
        pnlNavigation.add(bttnForo, java.awt.BorderLayout.PAGE_START);

        pnlMenu.add(pnlNavigation, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(pnlMenu, java.awt.BorderLayout.LINE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnForo;
    private javax.swing.JButton bttnLogout;
    private javax.swing.JButton bttnPerfil;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlNavigation;
    // End of variables declaration//GEN-END:variables
}
