package arquitecturaproyecto;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;

public class principal extends javax.swing.JFrame {
    
    private menu pnlMenu = new menu();
    private login pnlLogin = null;
    private registro pnlRegistro = null;
    private perfil pnlPerfil = null;
    private foro pnlForo = null;
    private eventos pnlEvento = null;

    public principal() {
        initComponents();
        pnlLogin = new login();
        pnlRegistro = new registro();
        this.setTitle("Iniciar Sesión");
        this.add(pnlLogin, BorderLayout.CENTER);

        pnlLogin.getBttnRegistrarse().addActionListener((ActionEvent e) -> {
            changeToRegister();
        });
        pnlLogin.getBttnIniciarSesion().addActionListener((ActionEvent e) -> {
            // Revisar en la BD del usuario.
        });
        pnlRegistro.getBttnRegresar().addActionListener((ActionEvent e) -> {
            changeToLogin();
        });
        pnlRegistro.getBttnConfirmarRegistrar().addActionListener((ActionEvent e) -> {
            // Registrar en la BD del usuario.
        });
    }

    private void changeToRegister() {
        pnlLogin.setVisible(false);
        pnlRegistro.setVisible(true);
        this.setTitle("Registrarse");
        this.add(pnlRegistro, BorderLayout.CENTER);
        this.validate();
    }

    private void changeToLogin() {
        pnlLogin.setVisible(true);
        pnlRegistro.setVisible(false);
        this.setTitle("Iniciar Sesión");
        this.add(pnlLogin, BorderLayout.CENTER);
        this.validate();
    }
    
    private void changeToForo() {
        /*pnlForo.setVisible(true);
        pnlEvento.setVisible(false);
        pnlPerfil.setVisible(false);
        
        bttnForo.setVisible(false);
        bttnPerfil.setVisible(true);
        this.setTitle("Foro de Eventos");
        this.add(pnlForo, BorderLayout.CENTER);
        this.validate();*/
    }
    private void changeToPerfil() {
        /*pnlForo.setVisible(false);
        pnlEvento.setVisible(false);
        pnlPerfil.setVisible(true);
        
        bttnForo.setVisible(true);
        bttnPerfil.setVisible(false);
        this.setTitle("Perfil");
        this.add(pnlPerfil, BorderLayout.CENTER);
        this.validate();*/
    }
    private void changeToEvento() {
        pnlForo.setVisible(false);
        pnlEvento.setVisible(true);
        pnlPerfil.setVisible(false);
        this.setTitle("Perfil");
        this.add(pnlEvento, BorderLayout.CENTER);
        this.validate();
    }
    private void navigateToLogin() {
//        if (frmLogin == null)
//            frmLogin = new loginRegistro();
//        else {
//            frmLogin = null;
//            frmLogin = new loginRegistro();
//        }
//        frmLogin.setExtendedState(MAXIMIZED_BOTH);
//        frmLogin.setVisible(true);
//        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1920, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
