/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package arquitecturaproyecto.vista;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author jocel
 */
public class foro extends javax.swing.JPanel {

    /**
     * Creates new form foro
     */
    public foro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNombreEvento = new javax.swing.JLabel();
        lblDescripcionEvento = new javax.swing.JLabel();
        bttnVerDetallesEvento = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        bttnEventoAnterior = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        bttnEventoSiguiente = new javax.swing.JButton();
        lblNumeroEvento = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblTotalEventos = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblDescripcionEvento1 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1620, 1080));
        setPreferredSize(new java.awt.Dimension(1620, 1080));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 978, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 228, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 980, 230));

        lblNombreEvento.setText("Nombre:");
        add(lblNombreEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, -1, -1));

        lblDescripcionEvento.setText("Dirección:");
        add(lblDescripcionEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, -1, -1));

        bttnVerDetallesEvento.setText("Ver más");
        bttnVerDetallesEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnVerDetallesEventoActionPerformed(evt);
            }
        });
        add(bttnVerDetallesEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 520, -1, -1));

        jLabel3.setText("Evento");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 570, -1, -1));

        bttnEventoAnterior.setText("Anterior");
        bttnEventoAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnEventoAnteriorActionPerformed(evt);
            }
        });
        add(bttnEventoAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 570, -1, -1));

        jLabel4.setText("de");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 570, -1, -1));

        bttnEventoSiguiente.setText("Siguiente");
        add(bttnEventoSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 570, -1, -1));
        add(lblNumeroEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 570, 30, 20));
        add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 210, 20));
        add(lblTotalEventos, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 570, 30, 20));
        add(lblDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 910, 20));
        add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, 910, 20));

        lblDescripcionEvento1.setText("Fecha:");
        add(lblDescripcionEvento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void bttnVerDetallesEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnVerDetallesEventoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttnVerDetallesEventoActionPerformed

    private void bttnEventoAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnEventoAnteriorActionPerformed
        //lblDireccionadd your handling code here:
    }//GEN-LAST:event_bttnEventoAnteriorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnEventoAnterior;
    private javax.swing.JButton bttnEventoSiguiente;
    private javax.swing.JButton bttnVerDetallesEvento;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDescripcionEvento;
    private javax.swing.JLabel lblDescripcionEvento1;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombreEvento;
    private javax.swing.JLabel lblNumeroEvento;
    private javax.swing.JLabel lblTotalEventos;
    // End of variables declaration//GEN-END:variables

    public JButton getBttnEventoAnterior() {
        return bttnEventoAnterior;
    }

    public JButton getBttnEventoSiguiente() {
        return bttnEventoSiguiente;
    }

    public JButton getBttnVerDetallesEvento() {
        return bttnVerDetallesEvento;
    }

    public JLabel getLblDireccion() {
        return lblDireccion;
    }

    public JLabel getLblFecha() {
        return lblFecha;
    }

    public JLabel getLblNombre() {
        return lblNombre;
    }

    public JLabel getLblNumeroEvento() {
        return lblNumeroEvento;
    }

    public JLabel getLblTotalEventos() {
        return lblTotalEventos;
    }

    
}
